/* eslint-disable @next/next/no-html-link-for-pages */
export default function BasesLegales() {
  return <main className="legalPage"><a href="/">← Volver al sorteo</a><p className="eyebrow">DOCUMENTO OFICIAL</p><h1>Bases legales del sorteo</h1><p className="legalUpdated">Última actualización: 15 de agosto de 2026</p>
    <section><h2>1. Organizador y aceptación</h2><p>El sorteo es organizado por Chicken Huerta (el “Organizador”). Participar implica conocer y aceptar íntegramente estas bases. El canal oficial es sorteo.chicken.huertadigital.net.pe y el número de contacto mostrado en el proceso de pago.</p></section>
    <section><h2>2. Vigencia y ámbito</h2><p>La fecha y hora de inicio y cierre son las publicadas en la portada, en hora de Perú. Pueden participar personas naturales mayores de 18 años con DNI peruano, número de WhatsApp activo y capacidad para recibir el premio en Perú.</p></section>
    <section><h2>3. Mecánica y precio</h2><p>Cada ticket cuesta el precio oficial mostrado en la portada al momento de la compra y contiene un código único. No existe límite de compra. El participante registra sus datos, paga el monto exacto por el canal oficial y adjunta un comprobante auténtico. Los tickets físicos deben figurar como vendidos y asociados a su comprador.</p></section>
    <section><h2>4. Validación, aprobación y rechazo</h2><p>La emisión de un código digital no confirma todavía su participación. El Organizador verifica cada pago. Solo los tickets con estado “aprobado”, o físicos “vendidos” e identificados, entran al sorteo. Un pago inexistente, duplicado, ilegible, incompleto, reversado o no coincidente puede ser rechazado y sus tickets anulados. El código de operación no puede reutilizarse.</p></section>
    <section><h2>5. Premios</h2><p>Se entregarán los dos premios identificados en la portada vigente. Las imágenes son referenciales; prevalecen los nombres y modelos allí indicados al momento de participar. Cada ticket aprobado participa en ambos premios, pero un mismo ticket no puede ganar dos veces.</p></section>
    <section><h2>6. Selección y publicación</h2><p>El sistema selecciona aleatoriamente un código entre los tickets elegibles y registra el resultado. Los premios se sortean por separado. Los ganadores se publican en la página oficial. El Organizador podrá verificar identidad, mayoría de edad, pago y titularidad antes de entregar.</p></section>
    <section><h2>7. Contacto y entrega</h2><p>El ganador será contactado por el WhatsApp registrado y deberá responder dentro de 7 días calendario. La entrega se coordinará directamente, previa firma de una constancia y presentación del DNI original. Los trámites, tributos, placa, seguro, traslado o gastos no descritos expresamente como parte del premio serán coordinados e informados al ganador antes de la entrega.</p></section>
    <section><h2>8. Descalificación y contingencias</h2><p>Se descalificará el fraude, suplantación, manipulación, información falsa o incumplimiento de estas bases. Si una falla técnica impide el sorteo, se reprogramará y anunciará por el canal oficial, preservando los tickets válidos. Ninguna modificación afectará derechos ya adquiridos ni reducirá premios sin comunicación clara.</p></section>
    <section><h2>9. Reclamos y responsabilidad</h2><p>Las consultas o reclamos se atienden por el canal oficial de contacto. El Organizador responde por ejecutar la promoción conforme a estas bases; no responde por errores de datos proporcionados por el participante, pérdida del ticket físico o indisponibilidad de servicios de terceros fuera de su control.</p></section>
    <section><h2>10. Datos personales</h2><p>Los datos se tratan para gestionar la compra, validar pagos, realizar el sorteo, contactar y publicar ganadores, atender consultas y cumplir obligaciones legales. Consulta el <a href="/privacidad">Aviso de privacidad</a>.</p></section>
  </main>;
}
